### ISSUE TITLE
Add TextMate grammar for .xxx syntax highlighting

### ISSUE THREAD

**Issue by Lorenz-N** [DAPSI-IDISS/semantic-crosswalk-editor#5]
If we define "xxx" as a custom language (without overlapping with the XML/XLS configurations) it obviously loses the syntax highlighting. And it seems it's not possible to just re-use or link the internal ones without [defining your own TextMate grammar](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#textmate-grammars). 

As a quick and dirty solution, we can just copy the syntaxes from [vscode-textmate](https://github.com/microsoft/vscode-textmate/blob/main/test-cases/themes/syntaxes/xml.json). There might be a better solution using [embeddedLanguages](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages) but I'm not sure if that's a good practice, especially if we want to add some custom highlighting for our extension later.

On a side note: Seems vscode just copied them from https://github.com/atom/language-xml and they converted them again from https://github.com/textmate/xml.tmbundle 🙄

**Comment by Lorenz-N** [comment]
Could be useful if we plan to keep or extend the custom grammar and integrate tests for it:  
https://github.com/PanAeon/vscode-tmgrammar-test

> Provides a way to test textmate grammars against a vscode engine using user-friendly plaintext files.

**Comment by svanteschubert** [comment]
Could we have a syntax highlighting grammar that highlight the 'xml' and 'semantic' view in different colors? Similar to the colors of the fonts of their left windows?

**Comment by Lorenz-N** [comment]
Moved this topic to https://github.com/DAPSI-IDISS/semantic-crosswalk-editor/issues/20
